/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnicalServicesRouteImport } from './routes/technical-services'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PhysicalWellnessRouteImport } from './routes/physical-wellness'
import { Route as MentalWellnessRouteImport } from './routes/mental-wellness'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminContactsRouteImport } from './routes/admin/contacts'

const TechnicalServicesRoute = TechnicalServicesRouteImport.update({
  id: '/technical-services',
  path: '/technical-services',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysicalWellnessRoute = PhysicalWellnessRouteImport.update({
  id: '/physical-wellness',
  path: '/physical-wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const MentalWellnessRoute = MentalWellnessRouteImport.update({
  id: '/mental-wellness',
  path: '/mental-wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/admin/contacts',
  path: '/admin/contacts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/mental-wellness': typeof MentalWellnessRoute
  '/physical-wellness': typeof PhysicalWellnessRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/technical-services': typeof TechnicalServicesRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/mental-wellness': typeof MentalWellnessRoute
  '/physical-wellness': typeof PhysicalWellnessRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/technical-services': typeof TechnicalServicesRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/mental-wellness': typeof MentalWellnessRoute
  '/physical-wellness': typeof PhysicalWellnessRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/technical-services': typeof TechnicalServicesRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/login'
    | '/mental-wellness'
    | '/physical-wellness'
    | '/pricing'
    | '/signup'
    | '/technical-services'
    | '/admin/contacts'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/login'
    | '/mental-wellness'
    | '/physical-wellness'
    | '/pricing'
    | '/signup'
    | '/technical-services'
    | '/admin/contacts'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/login'
    | '/mental-wellness'
    | '/physical-wellness'
    | '/pricing'
    | '/signup'
    | '/technical-services'
    | '/admin/contacts'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  MentalWellnessRoute: typeof MentalWellnessRoute
  PhysicalWellnessRoute: typeof PhysicalWellnessRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  TechnicalServicesRoute: typeof TechnicalServicesRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technical-services': {
      id: '/technical-services'
      path: '/technical-services'
      fullPath: '/technical-services'
      preLoaderRoute: typeof TechnicalServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physical-wellness': {
      id: '/physical-wellness'
      path: '/physical-wellness'
      fullPath: '/physical-wellness'
      preLoaderRoute: typeof PhysicalWellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mental-wellness': {
      id: '/mental-wellness'
      path: '/mental-wellness'
      fullPath: '/mental-wellness'
      preLoaderRoute: typeof MentalWellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/admin/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  MentalWellnessRoute: MentalWellnessRoute,
  PhysicalWellnessRoute: PhysicalWellnessRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  TechnicalServicesRoute: TechnicalServicesRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
